id: P006708
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:18:15.351412
source_metadata:
  id: bdr:W21510
  title: གསར་སྒྲིག་སྔགས་ཀློག་རྩ་འགྲེལ
  author: ''
  volumes:
    fc2569eca56c448e9d708ee8c3c33bc3:
      image_group_id: I1KG5136
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
